# Generated by Django 3.2.4 on 2021-06-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('userid', models.CharField(max_length=30, unique=True, verbose_name='아이디')),
                ('password', models.CharField(max_length=256, verbose_name='비밀번호')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='이메일')),
                ('gender', models.CharField(max_length=10, verbose_name='성별')),
                ('birthYear', models.IntegerField(default=1900, verbose_name='출생년도')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
