# Generated by Django 3.2.4 on 2021-06-23 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210624_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('/^가-힣+$/')], verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('/^[a-z0-9]+$/', 'only valid userid is required')], verbose_name='아이디'),
        ),
    ]
