# Generated by Django 3.2.4 on 2021-06-23 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210624_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('[가-힣+]')], verbose_name='이름'),
        ),
    ]
