# Generated by Django 3.2.4 on 2021-06-23 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210624_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthYear',
            field=models.IntegerField(verbose_name='출생년도'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[가-힣]+$', 'only valid name is required')], verbose_name='이름'),
        ),
    ]
