# Generated by Django 3.2.4 on 2021-06-23 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210624_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthYear',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)], verbose_name='출생년도'),
        ),
    ]
