# Generated by Django 3.2.4 on 2021-06-24 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_password'),
        ('accounts', '0014_alter_user_birthyear'),
    ]

    operations = [
    ]
