# Generated by Django 3.2.4 on 2021-07-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='수정날짜'),
        ),
    ]
