# Generated by Django 3.2.4 on 2021-06-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='구독서비스 명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('purchaseDay', models.IntegerField(verbose_name='결제일')),
                ('userid', models.CharField(max_length=256, verbose_name='유저정보')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='추가한 날짜')),
            ],
        ),
    ]
