# Generated by Django 3.2.4 on 2021-06-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribeDatas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribedatas',
            name='category',
            field=models.CharField(max_length=256, null=True, verbose_name='분류'),
        ),
    ]
