# Generated by Django 3.2.4 on 2021-07-04 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribeDatas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='price',
            field=models.IntegerField(default=0, verbose_name='가격'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='purchase_day',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='결제일'),
        ),
    ]
