# Generated by Django 3.2.4 on 2021-07-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribeDatas', '0002_alter_subscribe_user_pk'),
        ('subscribeDatas', '0002_auto_20210704_1210'),
    ]

    operations = [
    ]
