# Generated by Django 3.2.4 on 2021-06-30 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscribeDatas', '0002_subscribedatas_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeListData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=256, verbose_name='분류')),
                ('title', models.CharField(max_length=256, verbose_name='구독서비스명')),
            ],
        ),
        migrations.RemoveField(
            model_name='subscribedatas',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subscribedatas',
            name='title',
        ),
        migrations.RemoveField(
            model_name='subscribedatas',
            name='userid',
        ),
        migrations.AddField(
            model_name='subscribedatas',
            name='user_pk',
            field=models.ForeignKey(db_column='user_pk', default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.user', verbose_name='유저정보'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribedatas',
            name='subs_pk',
            field=models.ForeignKey(db_column='subs_pk', default=2, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='subscribeDatas.subscribelistdata', verbose_name='구독정보'),
            preserve_default=False,
        ),
    ]
